import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

import dynamic from 'next/dynamic'

const DynamicComponentWithNoSSR = dynamic(() => import('../components/video'), {
    ssr: false
})

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>
        <DynamicComponentWithNoSSR/>
    </div>
  )
}

export default Home
